import type { SourceDefinition } from "./types";

export const SOURCE_REGISTRY: SourceDefinition[] = [
  {
    id: "SRC-SITE-EVENTS",
    radar: "BEHAVIOR",
    name: "Gara Radar live events",
    status: "LIVE",
    cadence: "continuous",
    access: "internal Cloudflare Worker telemetry",
    url: "https://gara-radar.soliwkr.workers.dev",
  },
  {
    id: "SRC-BDNCP-OPEN",
    radar: "SUPPLY",
    name: "ANAC BDNCP Open Data",
    status: "DORMANT",
    cadence: "monthly source refresh",
    access: "public CSV/JSON datasets",
    url: "https://www.anticorruzione.it/en/-/portale-dei-dati-aperti-dell-autorita-nazionale-anticorruzione",
    notes:
      "Official source exists, but ingestion is not wired yet. DORMANT is intentional so runtime never pretends the feed is live.",
  },
  {
    id: "SRC-GSC",
    radar: "DEMAND",
    name: "Google Search Console",
    status: "REQUIRES_AUTH",
    cadence: "daily",
    access: "OAuth webmasters.readonly",
    url: "https://developers.google.com/webmaster-tools/v1/searchanalytics/query",
  },
  {
    id: "SRC-KEYWORD-MARKET",
    radar: "DEMAND",
    name: "Keyword market provider",
    status: "DORMANT",
    cadence: "weekly when provider exists",
    access: "provider not selected",
    notes:
      "Pre-site demand source for search volume, CPC, competition and trend snapshots. Provider-neutral normalizer exists; no provider is connected yet.",
  },
  {
    id: "SRC-GTRENDS",
    radar: "DEMAND",
    name: "Google Trends API alpha",
    status: "LIMITED_ACCESS",
    cadence: "daily/weekly when access exists",
    access: "Google alpha tester access required",
    url: "https://developers.google.com/search/apis/trends",
  },
  {
    id: "SRC-PAIN-WEB",
    radar: "PAIN",
    name: "Pain research web corpus",
    status: "MANUAL",
    cadence: "weekly",
    access: "approved search/research only",
    notes:
      "Forums, Reddit, YouTube comments, FAQ and review sources. Respect terms, rate limits and allowlists.",
  },
  {
    id: "SRC-COMPETITORS",
    radar: "COMPETITION",
    name: "Competitor monitor",
    status: "MANUAL",
    cadence: "weekly",
    access: "allowlisted public pages / approved research",
  },
  {
    id: "SRC-STRIPE",
    radar: "ECONOMIC",
    name: "Stripe revenue events",
    status: "REQUIRES_AUTH",
    cadence: "continuous once billing is live",
    access: "Stripe API/webhook credentials",
  },
  {
    id: "SRC-ANAC-REG",
    radar: "REGULATORY",
    name: "ANAC regulatory/platform change watch",
    status: "MANUAL",
    cadence: "weekly",
    access: "official ANAC public pages",
    url: "https://www.anticorruzione.it/",
  },
  {
    id: "SRC-FIRMOGRAPHIC",
    radar: "FIRMOGRAPHIC",
    name: "Firmographic provider TBD",
    status: "DORMANT",
    cadence: "monthly",
    access: "provider not selected",
  },
];
